### PR TITLE
Sketch out library version

### PR DESCRIPTION
**Pull request by bebraw**
First stab at a library version. I haven't really tested it. I'm more interested hearing your thoughts about the proposed API.

### CODE REVIEW

**Comment by tmcw** [comment]
I like the idea of making more of this usable as a library, but this changes the existing stream-based interface into a callback-based technique that requires the potentially gigantic sitemap file to be held in memory at the same time. I'd prefer to keep the library as something that streams data, and if people need a callback, then we can make it optional and use [concat-stream](https://github.com/maxogden/concat-stream) to support it.

**Comment by bebraw** [comment]
Great point. I'll change the implementation like that.

**Comment by bebraw** [comment]
I changed it to use a stream based API. Now it accepts a writer as the first parameter. Second parameter (object with the rest) is optional. There's also a little demo.

**Comment by tmcw** [comment]
:+1: thanks! merged in as part of https://github.com/tmcw/sitemap-static/pull/5, added tests, and released as 0.3.

**Comment by bebraw** [comment]
Great. Thanks a lot! :+1:

**Pull request merged**
